### ISSUE TITLE
Do not mutate requests and responses

### ISSUE THREAD

**Issue by tehnodev** [WyriHaximus/php-json-psr7#38]
Use (string) getBody() instead of  getBody()->getContents() to encode body. GetContents() method moves the body stream pointer to the end of stream and next getContents() will return empty string. You can call *_encode methods twice and see that in second call body is empty. Please fix that.

**Comment by WyriHaximus** [comment]
Good point, care to file a PR fixing this? Check the PSR for it and some implementations, and interesting enough not all of the implementations follow the PSR to the latter :zipper_mouth_face: .

**Comment by WyriHaximus** [comment]
@tehnodev which implementation of PSR-7 are you using? Just opened #39 but not getting any errors on locally changed tests

**Comment by WyriHaximus** [comment]
[`1.1.1`](https://github.com/WyriHaximus/php-json-psr7/releases/tag/1.1.1) has just been released with a fix for this
